name: GitHub Actions Deploy on server
run-name: ${{ github.actor }} is deploying on server 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
#  init:
  #    runs-on: ubuntu-latest
  #    strategy:
  #      matrix:
  #        node-version: [ 16.x ]
  #    steps:
  #      - uses: actions/checkout@v3
  #      # Setup ssh key
  #      - name: Setup key
  #        run: set -eu && mkdir "$HOME/.ssh" && echo "$" > "$HOME/.ssh/SSH_PRIVATE_KEY" && chmod 600 "$HOME/.ssh/SSH_PRIVATE_KEY"
  #      - name: Staring Node.js ${{ matrix.node-version }}
  #        uses: actions/setup-node@v3
  #        with:
  #          node-version: ${{ matrix.node-version }}
  #      # Install modules
  #      - name: Install modules
  #        run: npm ci
  #      - name: install server modules
  #        run: cd ./server && npm ci && cd ..
  #      # Deploy
  #      - name: Deploying to server
  #        run: rsync -e "ssh -p 20022 -i $HOME/.ssh/SSH_PRIVATE_KEY -o StrictHostKeyChecking=no" --archive --compress --delete . donaros4@donaros4.beget.tech:/home/d/donaros4/donaros4.beget.tech/QG-admin
  deploy:
    #    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Install modules
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm ci
      - name: install server modules
        run: cd ./server && npm ci && cd ..
      # Copy a folder recursively to a remote server
      - name: Copy folder content recursively to remote
        uses: Flaavius/ssh-commands@1.0
        with:
          local: .
          remote: ~/donaros4.beget.tech/QG-admin/test
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{secrets.SSH_PRIVATE_KEY}}